#! sh

echo "Setting everything up! First let's install Nix"
# Install Nix
sh <(curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install)
# Restart terminal
exec zsh
echo "Now we'll build apps & system settings"
# Build system
sudo nix run --extra-experimental-features "nix-command flakes" nix-darwin/master#darwin-rebuild -- switch --flake ~/nix#cooked
echo "Lastly, gotta copy over app configs"
python3 load-prefs.py
echo "Done setting up system!"